version: "3.8"
services:
  mongodb:
    image: mongo
    env_file:
      - env/.env.mdb.local
    container_name: ${MONGODB_CONTAINER_NAME}
    ports:
      - 27017:27017
    volumes:
      - data:/data

  mongo-express: 
    image: mongo-express
    env_file:
      - env/.env.me.local
    container_name: ${MONGOEXPRESS_CONTAINER_NAME}
    restart: always
    ports: 
      - 8081:8081

volumes:
  data: {}

networks:
  default:
    name: mongodb_network
