
version: “3.8”
services:
  mongodb:
    image: mongo
    container_name: ${MONGODB_CONTAINER_NAME}
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express: 
    image: mongo-express
    container_name: ${MONGOEXPRESS_CONTAINER_NAME}
    restart: always
    ports: 
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/


volumes:
  data: {}

networks:
  default:
    name: mongodb_network